### ISSUE TITLE
Workflow does not work on macOS Sierra

### ISSUE THREAD

**Issue by skyborn** [kmarchand/iCloudTabsAlfredWorkflow#4]
I love this workflow and use it everyday. Sadly the workflow does not work anymore on my freshly installed macOS Sierra. Can this great workflow be used on macOS Sierra? Thanks in advance!

**Comment by kmarchand** [comment]
Hey!  Really great to hear that nice feedback!  The only mac I have access to is for work and I haven't installed Sierra yet but as soon as I do I'll see if I can work it out.  Hopefully soon.

**Comment by kmarchand** [comment]
I just upgraded to Sierra and tested it and it seems to work fine for me.  The file with the iCloud tabs is in the same place for Sierra (~/Library/SyncedPreferences/com.apple.Safari.plist) and the workflow is working in the same way for me as it did with El Captain.

If you click on the "Show All Tabs" button (icon with two boxes) at the very top right of Safari and scroll down do you see the tabs listed on your other devices?

**Comment by skyborn** [comment]
Hi, first thanks for not forgetting me! 
Nice to know it works fine on Sierra. 

Yes, I can see the tabs listed on my other devices. 
Sadly the workflow still does not work on my freshly installed macOS Sierra.

Any ideas how we can resolve this?

Thanks in advance!

**Comment by kmarchand** [comment]
Not sure if this would help but you can go to the Alfred preferences, select the workflow, then turn on debugging mode (click the bug icon at the very top right) and switch the log to "All Information", and then once that's ready, try to run the workflow and see if any errors come up.

**Comment by skyborn** [comment]
This is what I get:

Starting debug for 'iCloud Tabs'

[2016-12-04 10:39:38][input.keyword] Processing output of 'action.script' with arg ''

**Comment by kmarchand** [comment]
That's a shame... I was hoping for some kind of error message.

I just uploaded a version of the main python script with some debug printing worked in;  `https://github.com/kmarchand/iCloudTabsAlfredWorkflow/blob/master/icloudtabs-debug.py`

Can you download that and then run it from terminal with `python icloudtabs-debug.py` and then copy the output and paste it here?

When I run that on my system I get this output in terminal:

```
STATUS: Temp path created ok: /var/folders/sj/n5s4cbd52v50rfv_yyldf4_c0000gn/T/safari_sync_plist_copy.plist
STATUS: com.apple.Safari.plist found ok
STATUS: plutil converted plist to XML ok


HostName = kmbp
ComputerName = kmbp


Device: km’s iPhone, Tab Count: 74
Device: kmbp, Tab Count: 17


kmbp is local device; tabs excluded from results
```

**Comment by skyborn** [comment]
Thanks!
Sadly I'm missing the devices output.


STATUS: Temp path created ok: var/folders/lp/s0t8n4vx7_9c95ztywdw4km40000gn/T/safari_sync_plist_copy.plist
STATUS: com.apple.Safari.plist found ok
STATUS: plutil converted plist to XML ok


HostName = iMac
ComputerName = iMac

**Comment by kmarchand** [comment]
Finally got around to it... should work now.  Issue was that they started encrypting the plist file I was using to find the iCloud tabs.  Alternate source found, and tested working on macOS 10.13

**Comment by ghost** [comment]
It works! Great! Thanks!
